version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: springdocker
    ports:
      - "3307:3307"
    networks:
      - spring-network

  spring-app:
    image: ens/springdocker:1.0
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/springdocker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - spring-network

networks:
  spring-network: